WeatherAppUsingDI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using ServiceContracts;
using Models;

namespace WeatherAppUsingDI.Controllers
{
    public class HomeController : Controller
    {
        private readonly IWeatherService _weatherService; // we create a reference to IWeatherService. It means that it can refer to any object inherited from IWeatherSerice

        public HomeController(IWeatherService weatherService)
        {
            _weatherService = weatherService; //we create constructor and execute Service code and Hardcoded data is loaded to weatherService parameter
        }



        [Route("/")]
        [Route("/weather")]
        public IActionResult Index()
        {
            List<CityWeather> cities = _weatherService.GetWeatherDetails(); //we return cities from loaded data using Dependency Injection
            return View(cities); // data is passed to Index view and displayed there
        }


        [Route("/weather/{cityCode}")]
        public IActionResult Details(string? cityCode) //cityCode is fetched from Index view by clicking specific link.
        {
            CityWeather city = _weatherService.GetWeatherByCityCode(cityCode); //Service function to match the citycode with data 
            return View(city); //data is passed to Details view
        }
    }
}

WeatherAppUsingDI/ViewComponents/DetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Models;

namespace WeatherAppUsingDI.ViewComponents
{
    public class DetailsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(CityWeather city) //data is passed with city parameter
        {
            return View(city); //data with city parameter is transferred to the view in ~/View/Shared/Components/Details/Default.cshtml
        }
    }
}

WeatherAppUsingDI/Views/Home/Details.cshtml
@model CityWeather; //using strong type view

@await Component.InvokeAsync("Details", new {
    city = Model
}); 

@*Invoking ViewComponent named "Details" as a part of project and passing selected city data to it*@

WeatherAppUsingDI/Views/Home/Index.cshtml
@model IEnumerable<CityWeather>

<!DOCTYPE html>
<html>
<body>
    <div class="container">
        @foreach (CityWeather city in Model)
        {
            <div class="box">
                <div class="city">@city.CityName</div>
                <div class="date-time">@city.DateAndTime.ToString("HH:mm")</div>
                <div class="temperature">@city.TemperatureFahrenheit°F</div>
                <div class="link">
                    <a href="/weather/@city.CityUniqueCode">Details</a>
                </div>
            </div>
        }

    </div>
</body>
</html>

WeatherAppUsingDI/Views/Shared/Components/Details/Default.cshtml
@model CityWeather

<div class="container">
    <div id="weather-box" class="box">
        <div id="city" class="city">@Model.CityName</div>
        <div id="date-time" class="date-time">@Model.DateAndTime.ToString("dd MMM yyyy | HH:mm")</div>
        <div id="temperature" class="temperature">@Model.TemperatureFahrenheit°F</div>
        <a href="/weather" class="link">Back</a>
    </div>
</div>


@*Data about selected city is being displayed in this partial view which is inside Details view*@

WeatherAppUsingDI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weather App</title>
    <link rel="stylesheet" href="/StyleSheet.css">
</head>
<body>
    <header>
        <div class="logo">
            <h1><strong>Weather App</strong></h1>
        </div>
    </header>

    @RenderBody()

    <footer>
        <div class="footer-text">
            <p>Weather App with MVC pattern</p>
        </div>
    </footer>
</body>
</html>